# Generated by Django 4.2.7 on 2025-04-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
