# Generated by Django 4.2.7 on 2025-05-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_loja_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='numero',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
