# Generated by Django 4.2.7 on 2025-05-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_loja_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('destaque', models.BooleanField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.loja')),
            ],
        ),
    ]
